name: HCPlayground
version: 1.0-SNAPSHOT
author: Terry NG
main: org.hcmc.hcplayground.HCPlayground
api-version: 1.13
softdepend:
  - Vault
  - WorldGuard

permissions:
  hc.*:
    # default, one of value as op, not op, true, false
    # true - everyone has permission
    # false - no one has permission, include op
    # op - only op has permission
    # not op - everyone but op has permission
    default: op
    description: Grant all permissions to player to handle the plugin
    children:
      - hc.all
  hc.quartermaster.*:
    default: op
    description: Grant permission to player as quartermaster, to manage all items include weapons, off-hand items, armor, accessories
    children:
      - hc.quartermaster.all

  hc.all:
    default: op
    description: Grant all permissions to player to handle the plugin
    children:
      - hc.reload
      - hc.quartermaster.all
  hc.quartermaster.all:
    description: Grant permission to player as quartermaster, to manage all items include weapons, off-hand items, armor, accessories
    default: op
    children:
      - hc.quartermaster.weapon
      - hc.quartermaster.armor
      - hc.quartermaster.off-hand
      - hc.quartermaster.accessory
      - hc.quartermaster.gui

  hc.reload:
    description: Permission to reload this plugin
    default: op

  hc.quartermaster.use:
    description: Grant permission to player to use
    default: true
  hc.quartermaster.weapon:
    description: Grant permission to player to manage weapon
    default: op
  hc.quartermaster.armor:
    description: Grant permission to player to manage armor
    default: op
  hc.quartermaster.off-hand:
    description: Grant permission to player to manage off-hand
    default: op
  hc.quartermaster.accessory:
    description: Grant permission to player to manage accessory
    default: op
  hc.quartermaster.gui:
    description: Grant permission to player to manage items from chest dialog
    default: op
