recipe1:
  name: name1
  shape:
    - 'A    B'
    - ' A  B '
    - '  AB  '
    - '  BA  '
    - ' B  A '
    - 'B    A'
  ingredients:
    A: stick
    B: stone
  amount:
    A: 4
    B: 5
  result: chest
  group: group1
