name: HCPlayground
version: 1.4.18.2-SNAPSHOT
authors:
  - Terry NG
main: org.hcmc.hcplayground.HCPlayground
api-version: 1.13
depend:
  - Multiverse-Core
  - PlaceholderAPI
  - Parkour
  - WorldGuard
softdepend:
  - Vault
